# -*- coding: utf-8 -*-
"""plot_stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izUEjPOb6oPmDUT1oXZ0FrNg5OIMUI9A
"""

import matplotlib.pyplot as plt
import seaborn as sns

## Change this to the player names that you want.
players = ['Heuristic 2', "Pulkit's Heuristic"]

games = [f'{players[0]} Goes First', f'{players[1]} Goes First']

## Edit the below 3 with the data. 0 index is for when Players[0] goes first, sly for Players[1].
player_1_wins = [13,11]
player_2_wins = [5,6]
ties = [7,8]

# Create a bar plot for the number of wins
sns.set(style="whitegrid", palette="pastel")
plt.figure(figsize=(10, 6))

bar_width = 0.25
index = range(len(players))

bar1 = plt.bar(index, player_1_wins, bar_width, label=f'{players[0]} Wins', color='skyblue')
bar2 = plt.bar([i + bar_width for i in index], player_2_wins, bar_width, label=f'{players[1]} Wins', color='lightcoral')
bar3 = plt.bar([i + 2*bar_width for i in index], ties, bar_width, label='Tie', color='aquamarine')

# Add labels and title
# plt.xlabel('Games', fontsize=14)
plt.ylabel('Number of Games Won', fontsize=14)
plt.title(f'Game Between "{players[0]}" and "{players[1]}"', fontsize=16)
plt.xticks([i + bar_width for i in index], games)
plt.legend()

# Annotate bars with labels inside the bars
# for i, v in enumerate(player_1_wins):
#     plt.text(i, v / 2, f'{players[0]}\n Wins', color='darkblue', ha='center', va='center', fontsize=10, rotation=None)
# for i, v in enumerate(player_2_wins):
#     plt.text(i + bar_width, v / 2, f'{players[1]}\n Wins', color='darkblue', ha='center', va='center', fontsize=10, rotation=None)
# for i, v in enumerate(ties):
#     plt.text(i + 2*bar_width, v / 2, 'Ties', color='darkblue', ha='center', va='center', fontsize=10, rotation=None)


# Annotate bars with Number on top of bars
for i, v in enumerate(player_1_wins):
    plt.text(i, v , str(v), color='darkblue', ha='center', va='bottom', fontsize=12)
for i, v in enumerate(player_2_wins):
    plt.text(i + bar_width, v , str(v), color='darkblue', ha='center', va='bottom', fontsize=12)
for i, v in enumerate(ties):
    plt.text(i + 2*bar_width, v , str(v), color='darkblue', ha='center', va='bottom', fontsize=12)

# Show the plot
plt.show()